# Generated by Django 6.1 on 2026-08-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaintassignment_complainthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, unique=True)),
                ('response_time_hours', models.PositiveIntegerField()),
                ('resolution_time_hours', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['response_time_hours'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_deadline', models.DateTimeField()),
                ('resolution_deadline', models.DateTimeField()),
                ('response_completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_breached', models.BooleanField(default=False)),
                ('resolution_breached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='complaints.complaint')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_slas', to='complaints.slapolicy')),
            ],
        ),
    ]
