# Generated by Django 6.1 on 2026-09-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaintanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintanalysis',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
