# Generated by Django 6.1 on 2026-09-13 16:55

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_add_ai_explanation"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="ComplaintEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=768),
                ),
                (
                    "embedding_model",
                    models.CharField(max_length=100),
                ),
                (
                    "source_text_hash",
                    models.CharField(max_length=64),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "complaint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]