# Generated by Django 6.1 on 2026-09-13 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaintembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=5, max_digits=6)),
                ('detection_threshold', models.DecimalField(decimal_places=5, max_digits=6)),
                ('embedding_model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Duplicate'), ('REJECTED', 'Not a Duplicate')], default='PENDING', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates', to='complaints.complaint')),
                ('possible_duplicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_duplicate_of', to='complaints.complaint')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status', '-detected_at'], name='duplicate_status_detected_idx')],
                'constraints': [models.UniqueConstraint(fields=('complaint', 'possible_duplicate'), name='unique_complaint_duplicate_pair'), models.CheckConstraint(condition=models.Q(('complaint', models.F('possible_duplicate')), _negated=True), name='complaint_duplicate_not_self')],
            },
        ),
    ]
