# Generated by Django 6.1 on 2026-09-14 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaintduplicate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaint-evidence/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_completed', models.BooleanField(default=False)),
                ('evidence_type', models.CharField(blank=True, choices=[('ROAD_DAMAGE', 'Road Damage'), ('WATER_LEAKAGE', 'Water Leakage'), ('GARBAGE', 'Garbage / Waste'), ('STREET_LIGHTING', 'Street Lighting'), ('ELECTRICITY', 'Electricity'), ('PUBLIC_SAFETY', 'Public Safety'), ('SANITATION', 'Sanitation'), ('OTHER', 'Other')], max_length=30)),
                ('observations', models.TextField(blank=True)),
                ('severity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complaint_consistency', models.BooleanField(blank=True, null=True)),
                ('analysis_explanation', models.TextField(blank=True)),
                ('analysis_model', models.CharField(blank=True, max_length=100)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='complaints.complaint')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_complaint_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
