# Generated by Django 6.1 on 2026-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaintresolutionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintanalysis',
            name='detected_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='complaintanalysis',
            name='english_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaintanalysis',
            name='english_title',
            field=models.TextField(blank=True),
        ),
    ]
